BaseURL = "http://web-falkirklug.rhcloud.com/"
languageCode = "en-gb"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true
canonifyurls = true
Title = "Falkirk Linux Users Group"
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Nikola Tesla"
